app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    path:     /connect
    defaults: { _controller: AppBundle:Security:login }

admin_login_check:
    path:    /connect/check
    defaults: { _controller: AppBundle:Security:check }

dashboard:
    path:     /admin/dashboard
    defaults: { _controller: AppBundle:Default:dashboard }